version: "3.10"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=django-insecure-(nsrd9erukv%%x_7!5d1m$r=w_eskm!7u!z#vn-%q9^m7t@s_l
      - DEBUG=1
      - RECAPTCHA_PUBLIC_KEY=6LdIwJogAAAAAG6oeAeOdlz2VpEhB_Zr_COxo4q6
      - RECAPTCHA_SECRET_KEY=6LdIwJogAAAAADjYSsrcVi2GyzmTnaNs9ZgcSwXf
      - GOOGLE_API_KEY=AIzaSyAIEcTWtkuBZ_BNXbh6hEnmRdMIkFqWCds
    depends_on:
      - db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  postgres_data: